New Validation: Check for backend binaries if backend or alerting declared
grafana/plugin-validator pull request #190
Opened 2024-05-01 12:13 UTC by academo

Adds validation for backend, alerting and executable attributes in plugin.json

Closes https://github.com/grafana/plugin-validator/issues/174

Cases
    Alerting=true and backend=false: error
    backend=true and executable="": error
    backend=false and executable=".+": error
    backend=true, excutable=".+", binaries not found: error
    backend=true, executable=".+", binaries found: correct

2024-05-02 09:48 UTC, mckn approved these changes
Nice! LGTM!

2024-05-02 11:02 UTC, marefr requested changes
Great, some comments/suggestions

2024-05-02 11:02 UTC, marefr commented on pkg/analysis/passes/backendbinary/backendbinary.go
> +			"You have marked backend=true in your plugin.json but have not added a backend executable. Please add a backend executable to your plugin.json if your plugin has a bakend component or set backend=
```suggestion
			"You have marked backend=true in your plugin.json but have not added a backend executable. Please add a backend executable to your plugin.json if your plugin has a backend component or set backend=false",
```

2024-05-02 11:15 UTC, academo commented on pkg/analysis/passes/backendbinary/backendbinary.go
> +var binarySuffixes = []string{
Good idea. I took the implementation from the backenddebug code but I like the idea of checking the prefix/ I'll change it.

2024-05-02 12:10 UTC, marefr approved these changes
LGTM

Not sure if there's anything to consider for bundled plugins with a backend etc

2024-05-06 07:51 UTC, academo commented
> LGTM
> 
> Not sure if there's anything to consider for bundled plugins with a backend etc

yes. this setup is not considering bundled/nested plugins at all. I'll open a follow up PR to improve that case. I suspect it'll require more changes in the validator.

2024-05-06 07:51 UTC, merged